apiVersion: v1
kind: Pod
metadata:
  name: app-001
  labels:
    app: app-001
spec:
  containers:
    - name: app
      image: nginx:alpine
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: my-pvc
